#==============================
# SPRING
#==============================
spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${APPLICATION_AUTHORIZATION_URL:http://localhost:8080}/auth/realms/${APPLICATION_AUTHORIZATION_REALM:meetupon}/protocol/openid-connect/certs

#==============================
# KEYCLOAK ADMIN
#==============================
keycloak:
  realm: ${APPLICATION_AUTHORIZATION_REALM:meetupon}
  resource: auth-service
  auth-server-url: ${APPLICATION_AUTHORIZATION_URL:http://localhost:8080}/auth
  credentials:
    secret: ${AUTH_SERVICE_SECRET:XEN26R27FLIUvCIpf5agPVfv4oazqQ6v}

#==============================
# CONFIGURATION
#==============================
server:
  port: 8590

#==============================
# EUREKA
#==============================
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  server:
    wait-time-in-ms-when-sync-empty: 3000