#==============================
# SPRING
#==============================
spring:
  application:
    name: auth-service

#==============================
# CONFIGURATION
#==============================
server:
  port: 5000

#==============================
# EUREKA
#==============================
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    port: ${EUREKA_SERVER_PORT:8761}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000