#==============================
# SPRING
#==============================
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: ticket-route
          uri: ${TICKET_SERVICE_URL:http://localhost:5003}
          predicates:
            - Path=/api/v1/tickets/**,/api/v1/meetups/**
        - id: user-route
          uri: ${USER_SERVICE_URL:http://localhost:5001}
          predicates:
            - Path=/api/v1/users/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${APPLICATION_AUTHORIZATION_URL:http://localhost:8080}/auth/realms/${APPLICATION_AUTHORIZATION_REALM:microservicesdemo-app}
        registration:
          gateway-service-client:
            provider: keycloak
            client-id: ${APPLICATION_AUTHORIZATION_GATEWAY_CLIENT_ID:gateway-service}
            client-secret: ${APPLICATION_AUTHORIZATION_GATEWAY_CLIENT_SECRET:z6CbziQZdnPgHftVPkGy4Nlr0X3moQ2c}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

#==============================
# CONFIGURATION
#==============================
server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"

#==============================
# EUREKA
#==============================
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    port: ${EUREKA_SERVER_PORT:8761}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

