#==============================
# SPRING
#==============================
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: ticket-route
          uri: ${TICKET_SERVICE_URL:http://localhost:8585}
          predicates:
            - Path=/api/v1/tickets/**,/api/v1/meetups/**
        - id: auth-route
          uri: ${AUTH_SERVICE_URL:http://localhost:8590}
          predicates:
            - Path=/api/v1/auth/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APPLICATION_AUTHORIZATION_URL:http://localhost:8080}/auth/realms/${APPLICATION_AUTHORIZATION_REALM:meetupon}

#==============================
# CONFIGURATION
#==============================
server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"

#==============================
# EUREKA
#==============================
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  server:
    wait-time-in-ms-when-sync-empty: 3000
