#==============================
# SPRING
#==============================
spring:
  application:
    name: ticket-service
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:ticket}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${APPLICATION_AUTHORIZATION_URL:http://localhost:8080}/auth/realms/${APPLICATION_AUTHORIZATION_REALM:meetupon}/protocol/openid-connect/certs

#==============================
# CONFIGURATION
#==============================
server:
  port: 8585

#==============================
# EUREKA
#==============================
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  server:
    wait-time-in-ms-when-sync-empty: 3000