#==============================
# SPRING
#==============================
spring:
  application:
    name: user-service
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:users}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    initialization-mode: always

#==============================
# CONFIGURATION
#==============================
server:
  port: 5001

#==============================
# EUREKA
#==============================
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    port: ${EUREKA_SERVER_PORT:8761}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000