#==============================
# SPRING
#==============================
spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${APPLICATION_AUTHORIZATION_URL:http://localhost:8080}/auth/realms/${APPLICATION_AUTHORIZATION_REALM:microservicesdemo-app}/protocol/openid-connect/certs

#==============================
# KEYCLOAK ADMIN
#==============================
keycloak:
  realm: ${APPLICATION_AUTHORIZATION_REALM:microservicesdemo-app}
  resource: user-service
  auth-server-url: ${APPLICATION_AUTHORIZATION_URL:http://localhost:8080}/auth
  credentials:
    secret: tzStYujeRnqoReZPJDMDjPMPFXZ6ypwf

#==============================
# CONFIGURATION
#==============================
server:
  port: 8590

#==============================
# EUREKA
#==============================
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    port: ${EUREKA_SERVER_PORT:8761}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000