#==============================
# SPRING
#==============================
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  security:
    user:
      password: ${CONFIG_SERVER_PASSWORD:password}
      name: user

#==============================
# CONFIGURATION
#==============================
server:
  port: 8888

#==============================
# EUREKA
#==============================
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  server:
    wait-time-in-ms-when-sync-empty: 3000