#==============================
# SPRING
#==============================
spring:
  application:
    name: ticket-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      password: ${CONFIG_SERVER_PASSWORD:password}
      username: user

